<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Images\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Docs\**" />
    <EmbeddedResource Remove="Docs\**" />
    <None Remove="Docs\**" />
    <Page Remove="Docs\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Utils\OCRProvider.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Config.xml" />
    <None Remove="Images\background.png" />
    <None Remove="Images\create.png" />
    <None Remove="Images\error.png" />
    <None Remove="Images\exam.png" />
    <None Remove="Images\folder.png" />
    <None Remove="Images\hyper.png" />
    <None Remove="Images\load.png" />
    <None Remove="Images\menu_export.png" />
    <None Remove="Images\menu_game.png" />
    <None Remove="Images\Phonk\Caveira\caveira1.png" />
    <None Remove="Images\Phonk\Caveira\caveira2.png" />
    <None Remove="Images\Phonk\Caveira\caveira3.png" />
    <None Remove="Images\Phonk\Caveira\caveira4.png" />
    <None Remove="Images\Phonk\Caveira\caveira5.png" />
    <None Remove="Images\Phonk\Caveira\caveira6.png" />
    <None Remove="Images\Phonk\Caveira\caveira7.png" />
    <None Remove="Images\Phonk\Caveira\caveira8.png" />
    <None Remove="Images\Phonk\Caveira\caveira9.png" />
    <None Remove="Images\Phonk\Soundfx\phonk1.mp3" />
    <None Remove="Images\Phonk\Soundfx\phonk1.ogg" />
    <None Remove="Images\Phonk\Soundfx\phonk2.mp3" />
    <None Remove="Images\Phonk\Soundfx\phonk2.ogg" />
    <None Remove="Images\Phonk\Soundfx\phonk3.mp3" />
    <None Remove="Images\Phonk\Soundfx\phonk3.ogg" />
    <None Remove="Images\Phonk\Soundfx\phonk4.mp3" />
    <None Remove="Images\Phonk\Soundfx\phonk4.ogg" />
    <None Remove="Images\Phonk\Soundfx\phonk5.mp3" />
    <None Remove="Images\Phonk\Soundfx\phonk5.ogg" />
    <None Remove="Images\Phonk\Soundfx\phonk6.mp3" />
    <None Remove="Images\Phonk\Soundfx\phonk6.ogg" />
    <None Remove="Images\Phonk\Soundfx\phonk7.mp3" />
    <None Remove="Images\Phonk\Soundfx\phonk7.ogg" />
    <None Remove="Images\Phonk\Soundfx\phonk8.mp3" />
    <None Remove="Images\Phonk\Soundfx\phonk8.ogg" />
    <None Remove="Images\Phonk\Soundfx\phonk9.mp3" />
    <None Remove="Images\Phonk\Soundfx\phonk9.ogg" />
    <None Remove="Images\project.png" />
    <None Remove="Images\Prompts\GenerateChapter.txt" />
    <None Remove="Images\Prompts\GenerateGal.txt" />
    <None Remove="Images\Prompts\GenerateQuestion.txt" />
    <None Remove="Images\Prompts\ReClustering.txt" />
    <None Remove="Images\result.png" />
    <None Remove="Images\search.png" />
    <None Remove="Images\type_card.png" />
    <None Remove="Images\type_classical.png" />
    <None Remove="Images\type_pdf.png" />
    <None Remove="Resources\char_state_tab.json" />
    <None Remove="Resources\cn_synonym.txt" />
    <None Remove="Resources\dict.txt" />
    <None Remove="Resources\idf.txt" />
    <None Remove="Resources\Models\sbert.onnx" />
    <None Remove="Resources\Models\xgboost_qvalue.onnx" />
    <None Remove="Resources\pos_prob_emit.json" />
    <None Remove="Resources\pos_prob_start.json" />
    <None Remove="Resources\pos_prob_trans.json" />
    <None Remove="Resources\prob_emit.json" />
    <None Remove="Resources\prob_trans.json" />
    <None Remove="Resources\stopwords.txt" />
    <None Remove="Resources\tokenizer.json" />
    <None Remove="Resources\vocab.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\Prompts\GenerateChapter.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Prompts\GenerateGal.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Prompts\GenerateOutline.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Config.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\icon.ico" />
    <Content Include="Images\Prompts\GenerateQuestion.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Prompts\ReClustering.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\char_state_tab.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\cn_synonym.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\dict.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\idf.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\pos_prob_emit.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\pos_prob_start.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\pos_prob_trans.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\prob_emit.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\prob_trans.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\stopwords.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\tokenizer.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\vocab.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Docnet.Core" Version="2.6.0" />
    <PackageReference Include="FreeSpire.Doc" Version="12.2.0" />
    <PackageReference Include="FreeSpire.Presentation" Version="9.3.0" />
    <PackageReference Include="FuzzyString" Version="1.0.0" />
    <PackageReference Include="jieba.NET" Version="0.42.2" />
    <PackageReference Include="LlmTornado" Version="3.8.12" />
    <PackageReference Include="LlmTornado.Agents" Version="1.0.11" />
    <PackageReference Include="Markdig.Wpf" Version="0.5.0.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.3" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.23.2" />
    <PackageReference Include="Microsoft.SemanticKernel.Abstractions" Version="1.72.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Onnx" Version="1.72.0-alpha" />
    <PackageReference Include="System.Management" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\background.png" />
    <Resource Include="Images\create.png" />
    <Resource Include="Images\error.png" />
    <Resource Include="Images\exam.png" />
    <Resource Include="Images\folder.png" />
    <Resource Include="Images\menu_export.png" />
    <Resource Include="Images\menu_game.png" />
    <Resource Include="Images\Phonk\Caveira\caveira1.png" />
    <Resource Include="Images\Phonk\Caveira\caveira2.png" />
    <Resource Include="Images\Phonk\Caveira\caveira3.png" />
    <Resource Include="Images\Phonk\Caveira\caveira4.png" />
    <Resource Include="Images\Phonk\Caveira\caveira5.png" />
    <Resource Include="Images\Phonk\Caveira\caveira6.png" />
    <Resource Include="Images\Phonk\Caveira\caveira7.png" />
    <Resource Include="Images\Phonk\Caveira\caveira8.png" />
    <Resource Include="Images\Phonk\Caveira\caveira9.png" />
    <Content Include="Images\Phonk\Soundfx\phonk1.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Phonk\Soundfx\phonk2.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Phonk\Soundfx\phonk3.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Phonk\Soundfx\phonk4.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Phonk\Soundfx\phonk5.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Phonk\Soundfx\phonk6.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Phonk\Soundfx\phonk7.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Phonk\Soundfx\phonk8.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Phonk\Soundfx\phonk9.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Models\sbert.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Models\xgboost_qvalue.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="Images\type_girl.png" />
    <Resource Include="Images\hyper.png" />
    <Resource Include="Images\load.png" />
    <Resource Include="Images\project.png" />
    <Resource Include="Images\result.png" />
    <Resource Include="Images\search.png" />
    <Resource Include="Images\type_card.png" />
    <Resource Include="Images\type_classical.png" />
    <Resource Include="Images\type_pdf.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Images\GalGame\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\external\AquaAvgFramework\AquaAvgFramework.csproj" />
    <ProjectReference Include="..\ReciteHelper.Core\ReciteHelper.Core.csproj" />
    <ProjectReference Include="..\ReciteHelper.Infrastructure\ReciteHelper.Infrastructure.csproj" />
  </ItemGroup>

    <Target Name="EnsureJiebaResources" BeforeTargets="Build">
    <PropertyGroup>
      <JiebaPackagePath>$(UserProfile)\.nuget\packages\jieba.net\$(JiebaNETVersion)\Resources</JiebaPackagePath>
    </PropertyGroup>
    
    <ItemGroup>
      <JiebaResources Include="$(JiebaPackagePath)\*.*" />
    </ItemGroup>
    
    <Copy SourceFiles="@(JiebaResources)" DestinationFolder="$(OutputPath)Resources" SkipUnchangedFiles="true" />
          
    <Message Text="已复制jieba资源文件到 $(OutputPath)Resources" Importance="high" />
  </Target>

</Project>
